### ISSUE TITLE
[Request] Download progress bar

### ISSUE THREAD

**Issue by Revo86** [robertomlsoares/leaflet-offline#1]
Loving this plugin!

How could I approach showing a progress bar, when the caching process has begun? Is there any variables I can get any status information from?

**Comment by robertomlsoares** [comment]
Glad that you like it, @Revo86!

Since you provide your own implementation of the saving process via the `tilesDb` parameter, you would need to implement it there.
If you look at the demo in the `gh-pages` branch you'll see that the `saveTiles` method is just a loop sending requests. In that case, you would use that as the progress since you have the total number of tiles to download and you know when each request completes. If you're using a different implementation, the general idea is still going to be pretty similar.

**Comment by Revo86** [comment]
allright got it working in a clunky way, thanks!

how come theres so many cancelled requests, once you want to download more than 500 tiles though?
